[erwan.privat@gmail.com]
source        = imaps://erwan.privat%40gmail.com:ecvu%20vmhn%20jjdz%20qhwo%20@imap.gmail.com:993
outgoing      = smtps://erwan.privat%40gmail.com:ecvu%20vmhn%20jjdz%20qhwo%20@smtp.gmail.com:587
default       = INBOX
from          = "Erwan Privat" <erwan.privat@gmail.com>
cache-headers = true

